name: kgino
description: KGino project

publish_to: 'none'

version: 3.0.0+300

# flutter packages pub run build_runner build --delete-conflicting-outputs
# flutter pub outdated
# flutter pub upgrade --major-versions
# $HOME/.pub-cache/bin/flutterfire configure

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  auto_route: ^4.2.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.11
  flutter_lints: ^2.0.1

flutter:
  generate: true
  uses-material-design: true

  #assets:
    #- assets/animations/
    #- assets/images/
