name: kgino
description: A new Flutter project.

publish_to: 'none'

version: 3.0.0+300

environment:
  sdk: ">=2.18.2 <3.0.0"

# flutter packages pub run build_runner build --delete-conflicting-outputs

# flutter pub outdated
# flutter pub upgrade

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  async: ^2.10.0
  audio_video_progress_bar: ^0.11.0
  cached_network_image: ^3.2.2
  collection: ^1.16.0
  dio: ^4.0.6
  dio_http_cache_lts: ^0.4.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  # flutter_form_builder: ^7.7.0
  # flutter_svg: ^1.1.6
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  go_router: ^5.1.1
  html: ^0.15.1
  # infinite_scroll_pagination: ^3.2.0
  intl: ^0.17.0
  jiffy: ^5.0.0
  json_annotation: ^4.7.0
  palette_generator: ^0.3.3+2
  scroll_to_index: ^3.0.1
  shared_preferences: ^2.0.15
  # speech_to_text: ^6.1.0
  video_player: ^2.4.7
  wakelock: ^0.6.2

dev_dependencies:
  build_runner: ^2.2.1
  flutter_lints: ^2.0.1
  freezed: ^2.1.1
  go_router_builder: ^1.0.15
  json_serializable: ^6.4.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Golos UI
      fonts:
        - asset: assets/fonts/Golos-UI/Golos-UI_Regular.ttf
          weight: 400
        - asset: assets/fonts/Golos-UI/Golos-UI_Medium.ttf
          weight: 500
        - asset: assets/fonts/Golos-UI/Golos-UI_Bold.ttf
          weight: 700