name: kgino
description: KGino project

publish_to: 'none'

version: 3.2.3+323

environment:
  sdk: ">=2.18.2 <3.0.0"

# dart run build_runner build --delete-conflicting-outputs
# dart run build_runner watch --delete-conflicting-outputs

# flutter pub outdated
# flutter pub upgrade

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  async: ^2.11.0
  audio_video_progress_bar: ^1.0.1
  cached_network_image: ^3.2.3
  collection: ^1.17.0
  crypto: ^3.0.2
  device_info_plus: ^8.2.0
  dio: ^5.1.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  flutter_hooks: ^0.18.6
  flutter_svg: ^1.1.6
  flutter_svg_provider: ^1.0.3
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  go_router: ^7.1.1
  html: ^0.15.2
  json_annotation: ^4.8.0
  intl: ^0.18.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  palette_generator: ^0.3.3+2
  path_provider: ^2.0.15
  scrollview_observer: ^1.10.1
  shared_preferences: ^2.1.0
  uuid: ^3.0.7
  video_player: ^2.6.1
  video_player_win: ^2.2.2
  wakelock: ^0.6.2
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  freezed: ^2.3.2
  isar_generator: ^3.1.0+1
  json_serializable: ^6.6.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Golos UI
      fonts:
        - asset: assets/fonts/Golos-UI/Golos-UI_Regular.ttf
          weight: 400
        - asset: assets/fonts/Golos-UI/Golos-UI_Medium.ttf
          weight: 500
        - asset: assets/fonts/Golos-UI/Golos-UI_Bold.ttf
          weight: 700