name: kgino
description: Просмотр TS.KG


publish_to: 'none'


version: 2.0.7+107

# flutter pub outdated
# flutter pub upgrade --major-versions
# flutter pub run build_runner build --delete-conflicting-outputs
# flutter build apk --split-per-abi --release


environment:
  sdk: ">=2.15.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  audio_video_progress_bar: ^0.10.0
  cached_network_image: ^3.2.0
  collection: ^1.15.0
  decorated_icon: ^1.2.1
  dio: ^4.0.6
  flutter_svg: ^1.0.3
  get: ^4.6.1
  get_storage: ^2.0.3
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  html: ^0.15.0
  http: ^0.13.4
  intl: ^0.17.0
  json_annotation: ^4.4.0
  palette_generator: ^0.3.2
  video_player: ^2.2.10
  wakelock: ^0.6.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.7
  flutter_lints: ^1.0.4
  json_serializable: ^6.1.4
  hive_generator: ^1.1.2


flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
