name: kgino
description: KGino project

publish_to: 'none'

version: 3.3.0+330

environment:
  sdk: ">=3.0.0 <4.0.0"

# dart run build_runner build --delete-conflicting-outputs
# dart run build_runner watch --delete-conflicting-outputs

# flutter pub outdated
# flutter pub upgrade

# flutter pub build apk --split-per-abi --release

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  async: ^2.11.0
  audio_video_progress_bar: ^2.0.0
  cached_network_image: ^3.3.0
  collection: ^1.17.0
  crypto: ^3.0.2
  device_info_plus: 8.2.2
  dio: ^5.3.1
  flutter_hooks: ^0.20.1
  flutter_svg: ^2.0.6
  freezed_annotation: ^2.2.0
  go_router: ^10.1.2
  html: ^0.15.4
  hooks_riverpod: ^2.4.0
  json_annotation: ^4.8.1
  intl: ^0.18.0
  isar: 4.0.0-dev.14
  isar_flutter_libs: 4.0.0-dev.14
  media_kit: ^1.1.7
  media_kit_video: ^1.1.8
  media_kit_libs_video: ^1.0.1
  palette_generator: ^0.3.3+3
  path_provider: ^2.1.1
  riverpod_annotation: ^2.1.5
  scrollview_observer: ^1.16.4
  shared_preferences: ^2.2.1
  skeletonizer: ^0.8.0
  uuid: ^3.0.7
  wakelock_plus: ^1.1.1
  youtube_player_flutter: ^8.1.2

  # when add surface container color, then remove
  material_color_utilities: ^0.5.0

  

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.3
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.2
  riverpod_lint: ^2.0.4

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Golos UI
      fonts:
        - asset: assets/fonts/Golos-UI/Golos-UI_Regular.ttf
          weight: 400
        - asset: assets/fonts/Golos-UI/Golos-UI_Medium.ttf
          weight: 500
        - asset: assets/fonts/Golos-UI/Golos-UI_Bold.ttf
          weight: 700