name: kgino
description: KGino project

publish_to: 'none'

version: 4.0.0+400

environment:
  sdk: ">=3.0.0 <4.0.0"

# dart run build_runner build --delete-conflicting-outputs
# dart run build_runner watch --delete-conflicting-outputs

# flutter pub outdated
# flutter pub upgrade

# flutter pub build apk --split-per-abi --release

dependencies:
  flutter:
    sdk: flutter
  # state management [riverpod]
  flutter_hooks: ^0.20.3
  hooks_riverpod: ^3.0.0-dev.3
  riverpod_annotation: ^3.0.0-dev.3

  # database [isar]
  isar: ^4.0.0-dev.14
  isar_flutter_libs: ^4.0.0-dev.14

  # media kit
#  media_kit: ^1.1.10+1
#  media_kit_video: ^1.2.4
#  media_kit_libs_video: ^1.0.4

  animations: ^2.0.10
  cached_network_image: ^3.3.0
  collection: ^1.18.0
  device_info_plus: ^9.1.1
  dio: ^5.4.0
  flutter_svg: ^2.0.9
  freezed_annotation: ^2.4.1
  go_router: ^12.1.3
  html: ^0.15.4
  intl: ^0.19.0
  json_annotation: ^4.8.1
  scrollview_observer: ^1.19.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  uuid: ^4.3.1

dependency_overrides:
  meta: ^1.11.0

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^3.0.1
  freezed: ^2.4.6
  json_serializable: ^6.7.1

  # state management [riverpod]
  custom_lint: ^0.5.7
  riverpod_generator: ^3.0.0-dev.11
  riverpod_lint: ^3.0.0-dev.4


flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Golos UI
      fonts:
        - asset: assets/fonts/Golos-UI/Golos-UI_Regular.ttf
          weight: 400
        - asset: assets/fonts/Golos-UI/Golos-UI_Medium.ttf
          weight: 500
        - asset: assets/fonts/Golos-UI/Golos-UI_Bold.ttf
          weight: 700