name: kgino
description: A new Flutter project.

publish_to: 'none'

version: 3.0.0+300

environment:
  sdk: ">=2.17.6 <3.0.0"

# flutter packages pub run build_runner build --delete-conflicting-outputs

# flutter pub outdated
# flutter pub upgrade

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_route: ^5.0.0
  get: ^5.0.0-beta.52
  flutter_form_builder: ^7.6.0
  intl: ^0.17.0
  json_annotation: ^4.6.0
  shared_preferences: ^2.0.15
  #video_player: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^5.0.0
  build_runner: ^2.2.0
  flutter_lints: ^2.0.1
  json_serializable: ^6.3.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Golos UI
      fonts:
        - asset: assets/fonts/Golos-UI/Golos-UI_Regular.ttf
          weight: 400
        - asset: assets/fonts/Golos-UI/Golos-UI_Medium.ttf
          weight: 500
        - asset: assets/fonts/Golos-UI/Golos-UI_Bold.ttf
          weight: 700