name: kgino
description: KGino project
publish_to: 'none'
version: 5.0.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # localizations
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # storage
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.3
  isar:
    hosted: https://pub.isar-community.dev
    version: ^4.0.3
  isar_flutter_libs:
    hosted: https://pub.isar-community.dev
    version: ^4.0.3

  # http helpers
  dio: ^5.4.3+1
  flutter_form_builder: ^9.2.1

  # routing
  go_router: ^14.1.3

  # state management
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^3.0.0-dev.3
  riverpod_annotation: ^3.0.0-dev.3

  # code generators / serializers
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  # информация об устройстве и приложении
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.0

  # images, icons, animations
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  flutter_svg_provider: ^1.0.7
  iconsax: ^0.0.8
  rive: ^0.13.4

  # video
  audio_video_progress_bar: ^2.0.3
  video_player: ^2.8.6
  youtube_player_flutter: ^9.0.1

  collection: ^1.18.0
  crypto: ^3.0.3
  html: ^0.15.4
  path_provider: ^2.1.3
  uuid: ^4.4.0
  wakelock_plus: ^1.1.4
  

dev_dependencies:
  build_runner: ^2.4.10
  custom_lint: ^0.6.4
  flutter_lints: ^4.0.0

  # state management
  riverpod_generator: ^3.0.0-dev.11
  riverpod_lint: ^3.0.0-dev.4

  # code generators / serializers
  freezed: ^2.5.3
  json_serializable: ^6.8.0

dependency_overrides:
  meta: ^1.14.0
  custom_lint: ^0.6.4
  custom_lint_core: ^0.6.3
  fading_edge_scrollview: ^4.1.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/animations/
