name: isar_generator
description: Code generator for the Isar Database. Finds classes annotated with @IsarCollection.
version: 2.5.0
repository: https://github.com/isar/isar
homepage: https://isar.dev
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  isar:
    path: ../isar
  build: ^2.2.1
  source_gen: ^1.2.1
  analyzer: ^5.13.0
  glob: ^2.0.2
  path: ^1.8.0
  dart_style: ^2.2.1
  dartx: ^1.0.0

dev_dependencies:
  lints: ^1.0.1
