// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyLhuCaatReuO6QkZ4eIJCqUTX-m1lFXE',
    appId: '1:1078901151339:web:7363f149c26cb6cf40832e',
    messagingSenderId: '1078901151339',
    projectId: 'kgino-fa5e3',
    authDomain: 'kgino-fa5e3.firebaseapp.com',
    storageBucket: 'kgino-fa5e3.appspot.com',
    measurementId: 'G-G3RG9KZJBQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvZXro7289zvB1n4TQl_qxFZpjUGjC9Eg',
    appId: '1:1078901151339:android:575c6875316ad24940832e',
    messagingSenderId: '1078901151339',
    projectId: 'kgino-fa5e3',
    storageBucket: 'kgino-fa5e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGzyZzO_dSq3ig4XghmAwkJgrXwHOlcgk',
    appId: '1:1078901151339:ios:d248797fcc63560d40832e',
    messagingSenderId: '1078901151339',
    projectId: 'kgino-fa5e3',
    storageBucket: 'kgino-fa5e3.appspot.com',
    iosClientId: '1078901151339-g9daemofo6lmmjusrj24vjl493ts0ibe.apps.googleusercontent.com',
    iosBundleId: 'kg.delletenebre.kgino',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGzyZzO_dSq3ig4XghmAwkJgrXwHOlcgk',
    appId: '1:1078901151339:ios:d248797fcc63560d40832e',
    messagingSenderId: '1078901151339',
    projectId: 'kgino-fa5e3',
    storageBucket: 'kgino-fa5e3.appspot.com',
    iosClientId: '1078901151339-g9daemofo6lmmjusrj24vjl493ts0ibe.apps.googleusercontent.com',
    iosBundleId: 'kg.delletenebre.kgino',
  );
}
